### ISSUE TITLE
Squashing commits in Pull Requests should be policy

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/ansible-galaxy-extras#107]
Hello @jmchilton @dannon @natefoo @martenson @bgruening 

I've merged a couple PRs here and hoping to merge more in this repo as well as the main galaxy repo and others. I see that when my pull request was merged it was not squashed, meaning there are some intermediary commits in this repo's history. I personally expected my commits to be squashed automatically using github's feature for doing so: https://help.github.com/articles/about-pull-request-merge-squashing/

I'm of the opinion that PRs should squash commits, but if you all disagree strongly, I can adapt my commit strategy. Please let me know what your thinking on this is.

**Comment by dannon** [comment]
@zfrenchee We've left it to authors to squash/rebase as they want.  Lots of people like keeping their atomic commits, with history, and I am against auto-squashing.

If you *want* something squashed at merge time, feel free to request it in the PR, though.

**Comment by zfrenchee** [comment]
Thanks @dannon !

**Comment by martenson** [comment]
@zfrenchee you can alternatively squash it locally and force push to your branch thus updating the PR to only have the squashed commits

**Comment by zfrenchee** [comment]
@martenson that requires some fancy git which don't know  -- much more in favor of github's magic button!

**Comment by mvdbeek** [comment]
If you want to learn about it:
[this](https://www.atlassian.com/git/tutorials/rewriting-history) is a pretty good tutorial on rewriting the commit history, it's definitely worth going through the examples.
And [this](http://chris.beams.io/posts/git-commit/) is also really worth reading if you're regularly working with git.

**Comment by martenson** [comment]
`git rebase -i` will get you started and `git push -f` is the other part;
test locally :)
