### ISSUE TITLE
Issue with PR #127

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy-extras#130]
Hi all,

the last PR https://github.com/galaxyproject/ansible-galaxy-extras/pull/127 breaks nginx restarts
in GalaxyKickStart https://github.com/ARTbio/GalaxyKickStart

```
RUNNING HANDLER [galaxyprojectdotorg.galaxy-extras : restart nginx] ************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/sbin/nginx", "-s", "reload"], "delta": "0:00:00.005885", "end": "2017-04-23 16:18:23.930299", "failed": true, "rc": 1, "start": "2017-04-23 16:18:23.924414", "stderr": "nginx: [emerg] open() \"/etc/nginx/conf.d/reports_auth.conf\" failed (2: No such file or directory) in /etc/nginx/nginx.conf:36", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
```

This may be an issue in templates/startup.sh.j2 (and the cp of reports_auth.conf.source) , I am investigating.

**Comment by drosofff** [comment]
https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/startup.sh.j2#L81
When is this condition true ?
I think that in most cases this block is ignored and we end up with reports_auth.conf.source in /etc/nginx/conf.d/ without reports_auth.conf and this crashes nginx when the handler is called

**Comment by abretaud** [comment]
Oops, sorry about that!
Would it work if we created a default empty reports_auth.conf from https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/tasks/nginx.yml?

**Comment by drosofff** [comment]
Probably. But there is maybe also some adaptations to make in the nginx.conf.j2 in that case ?
Apart from that, I change https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/tasks/nginx.yml#L14 with 
```
    - { src: 'nginx_reports_auth.conf.j2',  dest: '{{ nginx_conf_directory }}/reports_auth.conf' }
```
And it turns around the issue since the startup.sh script is not run unless you build a docker container, does it make sense ? So yes, maybe just templating another (empty ?) reports_auth.conf.j2 in the nginx.yml task as you propose would be sufficient.

The purpose of an intermediate reports_auth.conf.source file is not clear to me since I don't see clearly the purpose. But I guess that you already fight with an issue about that !

**Comment by abretaud** [comment]
I think just having an empty file should be enough.
I did this change because we need to make the auth part of the nginx conf file optional, and the nginx `if` does not do what you'd expect from a normal `if`.
Instead of the `if`, I include a file (nginx_reports_auth.conf) that is empty (no auth) or contains the basic_auth settings (if auth is enabled)

Is there an easy way to reproduce your problem?

**Comment by drosofff** [comment]
> Is there an easy way to reproduce your problem?

Pretty easy.

- spin off a VM with ansible=2.2.1.0
- git clone https://github.com/ARTbio/GalaxyKickStart.git
- cd GalaxyKickStart
- ansible-galaxy install -r requirements_roles.yml -p roles
- ansible-playbook -i inventory/galaxykickstart galaxy.yml

And you will see nginx crashing when the handler reloads nginx

**Comment by drosofff** [comment]
Ubuntu 14.04 !
