### ISSUE TITLE
munge installation when ubuntu 16.04

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy-extras#136]
As far as I can test the task https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/tasks/slurm.yml#L7 fails when ubuntu 16.04.
The issue I see comes from failure in `apt-get install munge` and is related to https://bugs.launchpad.net/ubuntu/+source/munge/+bug/1287624/comments/11.

If before running the playbook I install manually munge (with failure) and fix it as indicated
```
1. sudo systemctl edit --system --full munge.service
   While in the editor, append " --syslog" to the ExecStart line:
   ExecStart=/usr/sbin/munged --syslog

2. sudo systemctl enable munge.service

3. sudo systemctl start munge.service
```
Then, the task  https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/tasks/slurm.yml#L7 can run to completion.

Let me know if I missed something. If not I can work on a fix in the playbook

**Comment by drosofff** [comment]
@bgruening @jmchilton Should I close the issue or is this procedure in your attributions ?

**Comment by bgruening** [comment]
Feel free to close it :)

**Comment by bgruening** [comment]
And thanks!

**Comment by drosofff** [comment]
Happy to help !
