### ISSUE TITLE
additional support for pbs-clusters

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/ansible-galaxy-extras#17]
Hi, 

I made some changes to this role to include support for pbs-torque clusters, would you like me to send a pull request so these changes can be checked out/imported into the project?

Greetings
Matthias

**Comment by mvdbeek** [comment]
@matthdsm it's a bit late as a response, but personally I think that would be a good idea!

**Comment by bgruening** [comment]
For the Docker container it would be nice to switch it at run-time as well.

**Comment by matthdsm** [comment]
The pull request got merged, so I'll close this issue. 

Matthias
