### ISSUE TITLE
Post-startup script

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/ansible-galaxy-extras#184]
Hi there! I would like to have an option to provide an optional post-flight (or post startup script), which admins could use for all different things related to the configuration of the live instance (or other things that require a living galaxy instance, API accessible).

I would suggest adding some logic like:

```
if [[ -x $POST_START_SCRIPT ]]
   then
          # ephemeris installed already, maybe check for this
          galaxy-wait -g http://127.0.0.1 -v --timeout 120 > {{ galaxy_log_dir }}/post_start_actions.log && \
          $POST_START_SCRIPT >> {{ galaxy_log_dir }}/post_start_actions.log &
          # So this will wait for galaxy to start, without delaying the execution of the last tails commands that go after the user setup section.
fi
```

after or within https://github.com/galaxyproject/ansible-galaxy-extras/blob/24ad229a64dab6f1bf15bc825ee3cbfe6b018fbf/templates/startup.sh.j2#L426

as you might need user authentication and API Key.

Then admins would have the liberty to set a $POST_START_SCRIPT and do things like adding users (for a course for instance), adding workflows, setting quotas, etc.

I realise that this opens the door for trouble, but then is a price that comes with flexibility. For added security, we could have a standard location for the post start script, and refer to it directly (and then admins have to create the file with proper content).

Would this be well received as a contribution? Alternatively I can just PR the exact thing I need to have optionally done (which is to add workflows to a user and make them publishable).

**Comment by mvdbeek** [comment]
I have no concerns about this, the startup script is used by docker-galaxy-stable exclusively, so if @bgruening is OK with this I don't see a problem.

**Comment by bgruening** [comment]
Go for it. I like it :)

**Comment by pcm32** [comment]
Thanks guys, I have something now but having some issues with the user created through
https://github.com/galaxyproject/ansible-galaxy-extras/blob/7ab0cad82e71ed71678aa0443b5c7d9808439ed4/templates/startup.sh.j2#L430

Will open a separate issue to discuss that.
