### ISSUE TITLE
slurm-llnl package missing in 18.04

### ISSUE THREAD

**Issue by ianedwardthomas** [galaxyproject/ansible-galaxy-extras#241]
TASK [galaxyprojectdotorg.galaxy-extras : Install SLURM system packages]
fails with 
 (item=['slurm-llnl', 'slurm-drmaa-dev', 'python-psutil']) => {"ansible_loop_var": "item", "changed": false, "item": ["slurm-llnl", "slurm-drmaa-dev", "python-psutil"], "msg": "No package matching 'slurm-llnl' is available"}
because it looks like this package is no longer in ubuntu 18.04:
https://packages.ubuntu.com/search?suite=bionic&keywords=slurm-llnl

**Comment by abretaud** [comment]
This was fixed in #229
