### ISSUE TITLE
Ansible role testing

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/ansible-galaxy-extras#40]
As discussed with @mvdbeek it would be nice to have some travis testing included.
We propose two test for the beginning.
- [x] syntax check: https://servercheck.in/blog/testing-ansible-roles-travis-ci-github
- [x] build check with `docker build -t galaxy-docker`
- [ ] Build check with planemo machine

**Comment by jmchilton** [comment]
:heavy_plus_sign: :100:

Build check with planemo machine also.

**Comment by bgruening** [comment]
@jmchilton added it thanks. I will work in this as soon as I have stable traivs tested Docker Galaxy release.

**Comment by bgruening** [comment]
Ok, we made progress here in the last 6 month, awesome! planemo machine is still needed.
