### ISSUE TITLE
SFTP versus FTP, and what is the policy on this repo?

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/ansible-galaxy-extras#84]
Hello ansible-galaxy-extras developers! 
I am building a "flavor" of galaxy, working off of the great work of @bgruening and for our purposes, we want SFTP instead of FTP. I've introduced a PR (#83) which does this. I'd love if you had a look. 

But the real reason I'm raising this issue is that there are some other modifications I'd like to make, which aren't built into this "galaxy extras" repo yet, and I was wondering whether it would be appropriate to open those as pull requests or not. For example, I'd like to have an ansible playbook built in which configures HTTPS using letsencrypt/certbot so that when someone does `docker run` on @bgruening 's galaxy image or my own derivative image, their galaxy uses HTTPS by default (if they've configured it that way, using a `GALAXY_CONFIG` flag... see [Bjoern's README](https://github.com/bgruening/docker-galaxy-stable#galaxys-config-settings) for details).

Another modification I'd like to try is [Globus/GridFTP](https://www.globus.org/how-it-works) which I think fits here, since FTP is already here. 

Which brings me to my question: If I want to make a couple modifications like these, do they belong in this repo, perhaps turned off by default? The README to this repo says this is the "@natefoo" stack, and if these technologies are not part of your stack I should probably do this somewhere else, right?  @jmchilton  

Thanks!

**Comment by mvdbeek** [comment]
I would actually be in favour of splitting ansible-galaxy-extras, so that there would be ansible-galaxy-ftp, ansible-galaxy-cluster, ansible-galaxy-proxy and so on. If you want to go ahead and implement additional features we'd be happy to include them if they don't break existing functionality. We can always split these things into separate roles if the maintenance becomes too complicated. For GridFTP we'll have to consider the license (https://www.globus.org/legal/toolkit-license), but I think it's OK.

**Comment by zfrenchee** [comment]
Okay, in that case I'll open a couple more pull requests for additional features. I personally am new to this project but I think breaking it up would make less sense? It would be nice to have all the extras in one repo and then be able to pick and choose which roles you want from the repo, though I agree with too many more options, things could get out of hand.

**Comment by zfrenchee** [comment]
@jmchilton I see you are the BDFN so please let me know if this sounds okay.

**Comment by martenson** [comment]
Berufsverband Der Fachkosmetikerinnen Niedersachsen ?

**Comment by zfrenchee** [comment]
@martenson  https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/organization.rst

**Comment by martenson** [comment]
Dictator 👿

**Comment by bgruening** [comment]
@martenson too good!
@zfrenchee yes please add more options to this repo! This is awesome stuff!

**Comment by jmchilton** [comment]
This all sounds great - I am fine adding the behavior here.

Things being broken up is a better design - but I don't know how to get all the projects on the same page - I'd like docker-galaxy-stable and planemo-machine to look more like [ansible-artimed](https://github.com/ARTbio/ansible-artimed) but that is a lot of work and breaking things up more would mean even more work. I think it is all work doing - but we need to prioritize it and do the work. Until we are able to do that - I think putting more functionality here is absolutely fine.

If anyone has ideas for a middle ground while we break things up - like how we could have both one recipe and many recipes existing with the same set tasks - please let me know.

**Comment by bgruening** [comment]
I'm not so keen to split things up at the moment. I feel it increases complexity a lot, especially for beginners. Confirmed by several workshops - where the participants frequently claim that we have to many repositories and that it is hard to keep track and follow.

I'm preparing a huge SVG about the Galaxy ecosystem to at least explain the bigger projects, this will help a bit, but if not strictly needed for maintainability I would keep things together as much as possible.

Instead I'm more in favour of documenting our variables and naming schema. Making it consistent with @natefoo roles and deprecating old stuff (non-supervisor path?).

**Comment by martenson** [comment]
@bgruening should we improve upon https://galaxyproject.github.io/ ?

**Comment by bgruening** [comment]
@martenson I will definitely contribute this if it is ready

**Comment by natefoo** [comment]
Regarding the too many repos problem, I'd thought about creating a new org for the Ansible stuff.

**Comment by martenson** [comment]
@natefoo I think devs are able to orientate themselves in the github org and for everybody else we should have different forms of presenation (project homepage with focused sections and wiki)
