### ISSUE TITLE
How to launch an ansible task/role from startup.sh

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/ansible-galaxy-extras#95]
@jmchilton, @mvdbeek, @afgane, @martenson 
So for both my pull requests, #86 and #88, the tasks essentially rely on the specifics of the galaxy being launched. In #86, a username/pw which is unique to the galaxy admin is required, and in #88, a certificate specific to the galaxy fqdn is created. 

I'm using these tasks through @bgruening's beautiful docker image, but the problem is that the username/pw and certificate can't be bundled into the image -- they need to be given at `docker run` time. That means the tasks need to be called from `startup.sh` I believe. 

Should I establish a new ansible role for each of these, or is a set of tasks enough? How do I pass the variables (globus username/pw for #86 and galaxy fqdn for #88) to the role? Should I skip using ansible roles and just use shell scripts for each of those, which I can call from `startup.sh`?

Thanks!

**Comment by bgruening** [comment]
@zfrenchee I need more time to think about it, but my initial feeling is that a simple script is enough and no extra role is needed.

Also see this line for some inspiration: https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/startup.sh.j2#L8

**Comment by zfrenchee** [comment]
@bgruening the line you linked for inspiration calls an ansible task from within startup.sh. Is that what you think I should do?

**Comment by bgruening** [comment]
Just inspiration ;)
If I remember correctly I have done this to easily change a `ini` file. I was on my way to write a small python tool for it and found that build-in ansible function.

**Comment by zfrenchee** [comment]
I think I've come to realize that this isn't my actual issue -- going to open a new one =0
